/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_PANPROTO_C__
#define __RUST_PANPROTO_C__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {
    /** <No documentation available> */
    uint8_t * ptr;

    /** <No documentation available> */
    size_t len;

    /** <No documentation available> */
    size_t cap;
} Vec_uint8_t;

/** \brief
 *  Free a byte buffer returned by panproto-c.
 *
 *  The host must call this on every `repr_c::Vec<u8>` it receives, or
 *  memory leaks. Calling twice on the same buffer is undefined
 *  behavior; do not double-free. The Haskell binding's
 *  `pp_buf_free_at` glue zeroes the storage in place so a stale
 *  `Vec_uint8_t` record cannot be passed back; non-Haskell callers
 *  should follow the same discipline.
 *
 *  The drop is wrapped in [`std::panic::catch_unwind`] so that a stray
 *  panic in the deallocator (or in a `Vec` whose contents the host
 *  corrupted) cannot unwind across the FFI boundary, which is
 *  undefined behavior. A caught panic is silently suppressed; the
 *  host has no return channel here. This is the same panic-safety
 *  posture as every other entry point in this module.
 */
void
pp_buf_free (
    Vec_uint8_t buf);

/** \brief
 *  `&'lt [T]` but with a guaranteed `#[repr(C)]` layout.
 *
 *  # C layout (for some given type T)
 *
 *  ```c
 *  typedef struct {
 *  // Cannot be NULL
 *  T * ptr;
 *  size_t len;
 *  } slice_T;
 *  ```
 *
 *  # Nullable pointer?
 *
 *  If you want to support the above typedef, but where the `ptr` field is
 *  allowed to be `NULL` (with the contents of `len` then being undefined)
 *  use the `Option< slice_ptr<_> >` type.
 */
typedef struct slice_ref_uint8 {
    /** \brief
     *  Pointer to the first element (if any).
     */
    uint8_t const * ptr;

    /** \brief
     *  Element count
     */
    size_t len;
} slice_ref_uint8_t;

/** \brief
 *  Classify a full schema diff against a protocol, producing a
 *  compatibility report.
 *
 *  `proto` is a [`Resource::Protocol`](crate::handle::Resource) handle.
 *  `diff` is a CBOR-encoded `panproto_core::check::SchemaDiff` (as
 *  emitted by [`pp_check_diff_full`]). On success, `out` receives a
 *  CBOR-encoded `check::CompatReport` from `check::classify`.
 *
 *  Common failure modes are [`PpStatus::InvalidHandle`],
 *  [`PpStatus::TypeMismatch`] (when `proto` does not point at a
 *  `Protocol`), and [`PpStatus::Serialization`] (when `diff` is not a
 *  valid CBOR `check::SchemaDiff`).
 */
int32_t
pp_check_classify (
    uint32_t proto,
    slice_ref_uint8_t diff,
    Vec_uint8_t * out);

/** \brief
 *  Compute a full diff between two schemas via the `panproto-check`
 *  engine (20+ change categories).
 *
 *  `s1` and `s2` are [`Resource::Schema`](crate::handle::Resource)
 *  handles. On success, `out` receives a CBOR-encoded
 *  `panproto_core::check::SchemaDiff` produced by `check::diff`, with
 *  constraints, hyper-edges, variants, recursion points, usage modes,
 *  spans, and nominal-identity changes.
 *
 *  Common failure modes are [`PpStatus::InvalidHandle`] and
 *  [`PpStatus::TypeMismatch`].
 */
int32_t
pp_check_diff_full (
    uint32_t s1,
    uint32_t s2,
    Vec_uint8_t * out);

/** \brief
 *  Compute a lightweight structural diff between two schemas.
 *
 *  `s1` and `s2` are [`Resource::Schema`](crate::handle::Resource)
 *  handles. On success, `out` receives a CBOR-encoded
 *  [`SchemaDiff`](crate::api::helpers::SchemaDiff) (vertex/edge level)
 *  computed by [`crate::api::helpers::compute_diff`].
 *
 *  Common failure modes are [`PpStatus::InvalidHandle`] and
 *  [`PpStatus::TypeMismatch`] (when either handle does not point at a
 *  `Schema`).
 */
int32_t
pp_check_diff_simple (
    uint32_t s1,
    uint32_t s2,
    Vec_uint8_t * out);

/** \brief
 *  Render a compatibility report as a JSON document.
 *
 *  `report` is a CBOR-encoded `check::CompatReport`. On success, `out`
 *  receives the UTF-8 JSON bytes serialized from the
 *  [`serde_json::Value`] produced by `check::report_json`.
 *
 *  Returns [`PpStatus::Serialization`] when `report` is not a valid
 *  CBOR `check::CompatReport` or when the rendered JSON value cannot be
 *  serialized.
 */
int32_t
pp_check_report_json (
    slice_ref_uint8_t report,
    Vec_uint8_t * out);

/** \brief
 *  Render a compatibility report as human-readable text.
 *
 *  `report` is a CBOR-encoded `check::CompatReport`. On success, `out`
 *  receives the UTF-8 text bytes produced by `check::report_text`.
 *
 *  Returns [`PpStatus::Serialization`] when `report` is not a valid
 *  CBOR `check::CompatReport`.
 */
int32_t
pp_check_report_text (
    slice_ref_uint8_t report,
    Vec_uint8_t * out);

/** \brief
 *  Check whether a data set's schema matches a given schema.
 *
 *  `dataset_handle` is a data set handle; `schema_handle` is a
 *  [`Resource::Schema`](crate::handle::Resource) handle. On success,
 *  `out` receives a CBOR-encoded record (`stale`, `data_schema_id`,
 *  `target_schema_id`) by comparing `vcs::hash::hash_schema` outputs:
 *  the data set is stale when its stored schema id differs from the
 *  hash of the supplied schema.
 */
int32_t
pp_data_check_staleness (
    uint32_t dataset_handle,
    uint32_t schema_handle,
    Vec_uint8_t * out);

/** \brief
 *  Retrieve a data set as CBOR-encoded instances.
 *
 *  `dataset_handle` is a [`Resource::DataSet`](crate::handle::Resource)
 *  handle. On success, `out` receives the CBOR-encoded
 *  `Vec<WInstance>`. The stored payload is decoded and re-encoded so a
 *  corrupt carrier surfaces as a serialization error rather than
 *  returning opaque bytes.
 */
int32_t
pp_data_get_dataset (
    uint32_t dataset_handle,
    Vec_uint8_t * out);

/** \brief
 *  Round-trip and return a forward-migration complement carrier.
 *
 *  `complement` is the CBOR-encoded `Vec<Complement>` produced by a
 *  forward migration. The payload is decoded and re-encoded so a
 *  malformed carrier surfaces as a serialization error; on success,
 *  `out` receives the re-encoded complement bytes.
 */
int32_t
pp_data_get_migration_complement (
    slice_ref_uint8_t complement,
    Vec_uint8_t * out);

/** \brief
 *  Migrate a data set backward using a stored complement.
 *
 *  `dataset_handle` is the migrated (forward) data set handle;
 *  `complement` is the CBOR-encoded `Vec<Complement>` produced by the
 *  forward migration; `src_schema` and `tgt_schema` are
 *  [`Resource::Schema`](crate::handle::Resource) handles (the same
 *  pair, in the same order, as the forward migration). Auto-generates
 *  the lens and applies `lens::put` per record, pairing each migrated
 *  view with its complement. On success, `out_handle` receives a fresh
 *  [`Resource::DataSet`](crate::handle::Resource) handle re-anchored to
 *  the source schema.
 */
int32_t
pp_data_migrate_backward (
    uint32_t dataset_handle,
    slice_ref_uint8_t complement,
    uint32_t src_schema,
    uint32_t tgt_schema,
    uint32_t * out_handle);

/** \brief
 *  Migrate a data set forward between two schemas.
 *
 *  `dataset_handle` is a data set handle; `src_schema` and `tgt_schema`
 *  are [`Resource::Schema`](crate::handle::Resource) handles.
 *  Auto-generates a lens via `lens::auto_generate`, applies `lens::get`
 *  per record, and stores both the migrated data set and the
 *  complement carrier as new
 *  [`Resource::DataSet`](crate::handle::Resource) handles, returned via
 *  `out_data_handle` and `out_complement_handle`. The migrated data
 *  set is hashed against the target schema; the complement carrier
 *  keeps the source schema id and holds the CBOR-encoded
 *  `Vec<Complement>` in its `data` field.
 */
int32_t
pp_data_migrate_forward (
    uint32_t dataset_handle,
    uint32_t src_schema,
    uint32_t tgt_schema,
    uint32_t * out_data_handle,
    uint32_t * out_complement_handle);

/** \brief
 *  Store a data set from JSON, binding it to a schema.
 *
 *  `schema_handle` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle; `data_json` is raw JSON bytes (an array of records, decoded
 *  with `serde_json`; a bare object is treated as a one-element array).
 *  Each record is parsed via `inst::parse_json` against the schema's
 *  inferred root vertex, the instances are CBOR-encoded into a fresh
 *  `vcs::DataSetObject`, and the schema is hashed via
 *  `vcs::hash::hash_schema`. On success, `out_handle` receives a fresh
 *  [`Resource::DataSet`](crate::handle::Resource) handle.
 */
int32_t
pp_data_store_dataset (
    uint32_t schema_handle,
    slice_ref_uint8_t data_json,
    uint32_t * out_handle);

/** \brief
 *  Decide a refinement subsort relationship between two constraint sets.
 *
 *  `base_sort` is the UTF-8 shared base sort name; `sub_constraints`
 *  and `super_constraints` are CBOR-encoded `Vec<(String, String)>`
 *  of `(sort, value)` pairs. On success, `out_is_subsort` receives `1`
 *  when the sub-refinement refines at least as much as the
 *  super-refinement (it carries every constraint the super-refinement
 *  does), else `0`.
 */
int32_t
pp_enriched_refinement_subsort (
    slice_ref_uint8_t base_sort,
    slice_ref_uint8_t sub_constraints,
    slice_ref_uint8_t super_constraints,
    uint32_t * out_is_subsort);

/** \brief
 *  Type-check a GAT term against a theory and a typing context.
 *
 *  `expr` is a CBOR-encoded [`gat::Term`]; `theory` is a
 *  [`Resource::Theory`](crate::handle::Resource) handle; `context` is a
 *  CBOR-encoded `Vec<(String, String)>` mapping variable names to sort
 *  names. On success, `out` receives a CBOR-encoded `CheckOutput`
 *  record (`well_formed`, `output_sort`, `error`).
 *
 *  The result itself encodes well-formedness, so the entry point returns
 *  [`PpStatus::Ok`] for both a well-formed and an ill-formed term; only a
 *  malformed payload or a bad handle yields a non-`Ok` status. Calls
 *  [`gat::typecheck_term`].
 */
int32_t
pp_expr_check (
    slice_ref_uint8_t expr,
    uint32_t theory,
    slice_ref_uint8_t context,
    Vec_uint8_t * out);

/** \brief
 *  Evaluate a functional expression against an environment.
 *
 *  `expr` is a CBOR-encoded [`panproto_core::expr::Expr`]; `env` is a
 *  CBOR-encoded `Vec<(String, panproto_core::expr::Literal)>`. On success,
 *  `out` receives the CBOR-encoded [`panproto_core::expr::Literal`] result.
 *  Calls [`panproto_core::expr::eval`] with the default
 *  [`panproto_core::expr::EvalConfig`] (step and depth limits).
 */
int32_t
pp_expr_eval_func (
    slice_ref_uint8_t expr,
    slice_ref_uint8_t env,
    Vec_uint8_t * out);

/** \brief
 *  Evaluate a GAT term against a theory and a variable environment.
 *
 *  `expr` is a CBOR-encoded [`gat::Term`]; `env` is a CBOR-encoded
 *  `Vec<(String, gat::ModelValue)>`; `theory` is a
 *  [`Resource::Theory`](crate::handle::Resource) handle. On success,
 *  `out` receives the CBOR-encoded [`gat::ModelValue`] result.
 *
 *  The recursive evaluator mirrors `eval_term_recursive` in the WASM
 *  helpers: variables resolve against the environment, applications
 *  evaluate their arguments and consult the theory's operation table,
 *  nullary constants reduce to their name as a string, and other
 *  applications produce a structured `{ op, args, output_sort }` map.
 */
int32_t
pp_expr_eval_gat (
    slice_ref_uint8_t expr,
    slice_ref_uint8_t env,
    uint32_t theory,
    Vec_uint8_t * out);

/** \brief
 *  Parse expression source text into a `panproto-expr` AST.
 *
 *  `source` is the UTF-8 source bytes. On success, `out` receives the
 *  CBOR-encoded [`panproto_core::expr::Expr`]. Tokenizes via
 *  [`panproto_core::expr_parser::tokenize`] then parses via
 *  [`panproto_core::expr_parser::parse`]; either failure maps to
 *  [`FfiError::Operation`].
 */
int32_t
pp_expr_parse (
    slice_ref_uint8_t source,
    Vec_uint8_t * out);

/** \brief
 *  Check a model against a theory, returning equation violations.
 *
 *  `model` is a [`Resource::Model`] handle; `theory` is a
 *  [`Resource::Theory`] handle. On success, `out` receives a
 *  CBOR-encoded `Vec<String>` of violation descriptions (the `Debug`
 *  rendering of each `gat::EquationViolation`), empty when the model
 *  satisfies every equation. A satisfied and a violated model both
 *  return [`PpStatus::Ok`]; the verdict lives in the payload.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a
 *  bad handle, and [`PpStatus::Operation`] when checking itself fails (a
 *  missing carrier set, or an assignment count that exceeds the engine
 *  bound). Calls `gat::check_model`.
 */
int32_t
pp_gat_check_model (
    uint32_t model,
    uint32_t theory,
    Vec_uint8_t * out);

/** \brief
 *  Check the validity of a theory morphism.
 *
 *  `morphism` is a CBOR-encoded [`gat::TheoryMorphism`]; `domain` and
 *  `codomain` are [`Resource::Theory`] handles. On success, `out`
 *  receives a CBOR-encoded [`MorphismCheckResult`]. The result itself
 *  encodes validity, so the entry point returns [`PpStatus::Ok`] for
 *  both a valid and an invalid morphism; only a malformed payload or a
 *  bad handle yields a non-`Ok` status. Calls `gat::check_morphism`.
 */
int32_t
pp_gat_check_morphism (
    slice_ref_uint8_t morphism,
    uint32_t domain,
    uint32_t codomain,
    Vec_uint8_t * out);

/** \brief
 *  Compute the colimit of two theories over a shared base.
 *
 *  `t1`, `t2`, and `shared` are [`Resource::Theory`] handles. On
 *  success, `out_handle` receives a fresh [`Resource::Theory`] handle
 *  holding `gat::colimit_by_name(t1, t2, shared)`.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] if a
 *  handle is invalid or not a theory, and [`PpStatus::Operation`] if the
 *  colimit fails.
 */
int32_t
pp_gat_colimit (
    uint32_t t1,
    uint32_t t2,
    uint32_t shared,
    uint32_t * out_handle);

/** \brief
 *  Create a GAT theory from a CBOR spec.
 *
 *  `spec` is a CBOR-encoded [`gat::Theory`]. On success, `out_handle`
 *  receives a fresh [`Resource::Theory`] handle and [`PpStatus::Ok`] is
 *  returned. On CBOR decode failure, [`PpStatus::Serialization`] is
 *  returned and `out_handle` is left untouched.
 */
int32_t
pp_gat_create_theory (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Evaluate an operation in a model and return the resulting value.
 *
 *  `model` is a [`Resource::Model`] handle; `op_name` is the UTF-8
 *  operation name; `args` is a CBOR-encoded `Vec<ModelValue>` of
 *  arguments. On success, `out` receives the CBOR-encoded
 *  [`gat::ModelValue`] the operation produced. The operation's
 *  interpretation (a closure held in the model) is run in-process; only
 *  its inputs and output cross the boundary, so a handle-held model is
 *  fully evaluable from the host. Calls [`gat::Model::eval`].
 *
 *  Returns [`PpStatus::Serialization`] on a malformed argument payload,
 *  [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a bad
 *  model handle, and [`PpStatus::Operation`] when the operation is not in
 *  the model or its interpretation fails.
 */
int32_t
pp_gat_eval_in_model (
    uint32_t model,
    slice_ref_uint8_t op_name,
    slice_ref_uint8_t args,
    Vec_uint8_t * out);

/** \brief
 *  Construct a bounded approximation of the free (initial) model of a
 *  theory.
 *
 *  `theory` is a [`Resource::Theory`] handle; `config` is an optional
 *  CBOR-encoded free-model config (`{max_depth, max_terms_per_sort}`); an
 *  empty slice selects the engine defaults. On success, `out_handle`
 *  receives a fresh [`Resource::Model`] handle holding the constructed
 *  model.
 *
 *  The model is held by handle rather than serialized: a model's
 *  operation interpretations are closures (`Arc<dyn Fn(...)>`) that
 *  cannot cross the ABI. Calls `gat::free_model`.
 *
 *  Returns [`PpStatus::Serialization`] on a malformed config payload,
 *  [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a bad
 *  theory handle, and [`PpStatus::Operation`] when free-model
 *  construction fails (a cyclic sort dependency or an exceeded term
 *  bound).
 */
int32_t
pp_gat_free_model (
    uint32_t theory,
    slice_ref_uint8_t config,
    uint32_t * out_handle);

/** \brief
 *  Migrate a model through a theory morphism.
 *
 *  `model` is a CBOR-encoded sort-interpretation map
 *  (`HashMap<String, Vec<ModelValue>>`); `morphism` is a CBOR-encoded
 *  [`gat::TheoryMorphism`]. On success, `out` receives the CBOR-encoded
 *  reindexed sort interpretations.
 *
 *  Only sort interpretations cross the boundary. A [`gat::Model`] also
 *  carries operation interpretations as closures (`Arc<dyn Fn(...)>`),
 *  which cannot be serialized; reindexing those is the host's
 *  responsibility once the sorts have moved. The reindex mirrors
 *  `panproto_wasm::api::gat::migrate_model`: for each `(domain_sort,
 *  codomain_sort)` entry in the morphism's `sort_map`, the codomain
 *  sort's carrier is copied to the domain sort name.
 */
int32_t
pp_gat_migrate_model (
    slice_ref_uint8_t model,
    slice_ref_uint8_t morphism,
    Vec_uint8_t * out);

/** \brief
 *  Emit a model's full carrier: its sort-interpretation map.
 *
 *  `model` is a [`Resource::Model`] handle. On success, `out` receives
 *  the CBOR-encoded `HashMap<String, Vec<ModelValue>>` of the model's
 *  `sort_interp`: each sort name mapped to its carrier set. This is the
 *  extractable data half of a model (the operation interpretations stay
 *  in-process); paired with [`pp_gat_eval_in_model`], a handle-held model
 *  is both evaluable and its carrier serializable.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a
 *  bad model handle.
 */
int32_t
pp_gat_model_sort_interp (
    uint32_t model,
    Vec_uint8_t * out);

/** \brief
 *  Serialize the theory behind a handle to CBOR.
 *
 *  `theory` is a [`Resource::Theory`] handle. On success, `out` receives
 *  the CBOR-encoded [`gat::Theory`] in the same shape
 *  [`pp_gat_create_theory`] decodes, so an engine-produced theory (a
 *  colimit result, for instance) can be reified by the host and fed back
 *  in.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a
 *  bad handle.
 */
int32_t
pp_gat_serialize_theory (
    uint32_t theory,
    Vec_uint8_t * out);

/** \brief
 *  Compute the shortest distance between two schemas in a lens graph.
 *
 *  `graph` is a CBOR-encoded `Vec<GraphEdge>`; `source_schema` and
 *  `target_schema` are UTF-8 schema names. On success, `out_distance`
 *  receives the distance ([`f64::INFINITY`] when unreachable, the schemas
 *  are unknown, or no path exists). Calls `LensGraph::distance`.
 */
int32_t
pp_graph_conversion_distance (
    slice_ref_uint8_t graph,
    slice_ref_uint8_t source_schema,
    slice_ref_uint8_t target_schema,
    double * out_distance);

/** \brief
 *  Compute the fiber of a compiled migration at a target anchor.
 *
 *  `instance` and `migration` are CBOR-encoded [`WInstance`] and
 *  [`CompiledMigration`];
 *  `target_anchor` is the UTF-8 anchor name. On success, `out` receives a
 *  CBOR-encoded `Vec<u32>` of source node IDs whose remapped anchor equals
 *  `target_anchor`. Calls `inst::fiber_at_anchor`.
 */
int32_t
pp_graph_fiber_at (
    slice_ref_uint8_t instance,
    slice_ref_uint8_t migration,
    slice_ref_uint8_t target_anchor,
    Vec_uint8_t * out);

/** \brief
 *  Compute fibers for all target anchors at once.
 *
 *  `instance` and `migration` are CBOR-encoded `WInstance` and
 *  `CompiledMigration`. On success, `out` receives a CBOR-encoded
 *  `HashMap<String, Vec<u32>>` partitioning the source nodes (every
 *  source node appears in exactly one fiber). Calls
 *  `inst::fiber_decomposition`.
 */
int32_t
pp_graph_fiber_decomposition (
    slice_ref_uint8_t instance,
    slice_ref_uint8_t migration,
    Vec_uint8_t * out);

/** \brief
 *  Construct the internal hom schema `[S, T]`.
 *
 *  `source_schema` and `target_schema` are CBOR-encoded
 *  [`Schema`](panproto_core::schema::Schema) values. For each source
 *  vertex in `S`, the hom schema contains choice and backward vertices
 *  encoding all structure-preserving maps from `S` to `T`. On success,
 *  `out` receives the CBOR-encoded hom `Schema`. Calls `inst::hom_schema`.
 */
int32_t
pp_graph_poly_hom (
    slice_ref_uint8_t source_schema,
    slice_ref_uint8_t target_schema,
    Vec_uint8_t * out);

/** \brief
 *  Find the cheapest conversion path between two schemas in a lens graph.
 *
 *  `graph` is a CBOR-encoded `Vec<GraphEdge>` (each with `source`,
 *  `target`, and a CBOR-encoded `ProtolensChain`); `source_schema` and
 *  `target_schema` are UTF-8 schema names. On success, `out` receives a
 *  CBOR-encoded `{ cost, steps }` record giving the total cost and the
 *  protolens step names along the shortest path. Calls
 *  `LensGraph::preferred_path`; returns [`PpStatus::Operation`] when no
 *  path exists.
 */
int32_t
pp_graph_preferred_path (
    slice_ref_uint8_t graph,
    slice_ref_uint8_t source_schema,
    slice_ref_uint8_t target_schema,
    Vec_uint8_t * out);

/** \brief
 *  Free a handle, marking its slab slot reusable.
 *
 *  Double-free is safe: a freed slot stays freed.
 */
int32_t
pp_handle_free (
    uint32_t handle);

/** \brief
 *  Find the single best-quality morphism between two schemas.
 *
 *  Arguments match [`pp_hom_find_morphisms`]. On success, `out`
 *  receives a CBOR-encoded `Option<FoundMorphismWire>`. Calls
 *  `hom_search::find_best_morphism`.
 */
int32_t
pp_hom_find_best_morphism (
    uint32_t src,
    uint32_t tgt,
    slice_ref_uint8_t opts,
    Vec_uint8_t * out);

/** \brief
 *  Find structure-preserving morphisms between two schemas.
 *
 *  `src` and `tgt` are [`Resource::Schema`](crate::handle::Resource)
 *  handles. `opts` is a CBOR-encoded `SearchOptionsWire` mirroring
 *  `panproto_core::mig::hom_search::SearchOptions`. On success, `out`
 *  receives a CBOR-encoded `Vec<FoundMorphismWire>` (each with
 *  `vertex_map`, `edge_map`, and `quality`), already ranked by
 *  descending quality. Calls `hom_search::find_morphisms`.
 */
int32_t
pp_hom_find_morphisms (
    uint32_t src,
    uint32_t tgt,
    slice_ref_uint8_t opts,
    Vec_uint8_t * out);

/** \brief
 *  Induce a migration from a theory morphism and source/target schemas.
 *
 *  `theory_morphism` is a CBOR-encoded `gat::TheoryMorphism`; `src` and
 *  `tgt` are [`Resource::Schema`](crate::handle::Resource) handles. On
 *  success, `out` receives the CBOR-encoded induced `SchemaMorphism`
 *  and `out_handle` receives a fresh
 *  [`Resource::MigrationWithSchemas`](crate::handle::Resource) handle
 *  (the compiled `Delta_F` pullback bundled with its anchoring schemas).
 *  Calls `mig::cascade::induce_migration_from_theory`.
 */
int32_t
pp_hom_induce_migration_from_theory (
    slice_ref_uint8_t theory_morphism,
    uint32_t src,
    uint32_t tgt,
    Vec_uint8_t * out,
    uint32_t * out_handle);

/** \brief
 *  Induce a schema morphism from a theory morphism and a source schema.
 *
 *  `theory_morphism` is a CBOR-encoded
 *  `panproto_core::gat::TheoryMorphism`. `src` is a
 *  [`Resource::Schema`](crate::handle::Resource) handle. On success,
 *  `out` receives a CBOR-encoded `panproto_core::schema::SchemaMorphism`.
 *  Calls `mig::cascade::induce_schema_morphism`.
 */
int32_t
pp_hom_induce_schema_morphism (
    slice_ref_uint8_t theory_morphism,
    uint32_t src,
    Vec_uint8_t * out);

/** \brief
 *  Convert a found morphism into a compiled migration.
 *
 *  `morphism` is a CBOR-encoded `FoundMorphismWire`. The found
 *  morphism is lowered to a `mig::Migration` via
 *  `hom_search::morphism_to_migration`, then compiled against the
 *  minimal schemas implied by its surviving vertex and edge sets. On
 *  success, `out_handle` receives a fresh
 *  [`Resource::Migration`](crate::handle::Resource) handle.
 */
int32_t
pp_hom_morphism_to_migration (
    slice_ref_uint8_t morphism,
    uint32_t * out_handle);

/** \brief
 *  Initialize the panproto-c runtime.
 *
 *  Installs a process-global Rust panic hook that suppresses the
 *  default stderr output. Panics are still observable: every entry
 *  point in this module catches them via [`crate::panic::guard`] and
 *  stashes the message in the thread-local last-error slot, which
 *  the host retrieves via [`pp_last_error_take`]. Without this hook
 *  the default Rust handler would print every caught panic to
 *  stderr before `guard` could report it, which is noisy and
 *  surprising for hosts that already report errors through the
 *  status-code channel.
 *
 *  Idempotent: calling more than once just re-installs the same
 *  hook. Always returns [`PpStatus::Ok`]. The slab and last-error
 *  slots are thread-local `RefCell`s that initialize lazily, so they
 *  do not need explicit setup.
 */
int32_t
pp_init (void);

/** \brief
 *  Count the nodes in a W-type instance.
 *
 *  `instance` is a CBOR-encoded `WInstance`. On success, `out_count`
 *  receives the node count. Calls `WInstance::node_count`.
 */
int32_t
pp_inst_element_count (
    slice_ref_uint8_t instance,
    uint32_t * out_count);

/** \brief
 *  Parse JSON bytes into a W-type instance.
 *
 *  `schema_handle` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle. `json` is raw JSON bytes (decoded with `serde_json`, not
 *  CBOR). `root_vertex` is a UTF-8 string selecting the root vertex
 *  (empty infers it). On success, `out` receives a CBOR-encoded
 *  `WInstance`. Calls `inst::parse_json`.
 *
 *  Root-vertex precedence mirrors the WASM boundary's
 *  `json_to_instance_with_root`:
 *  1. the explicit caller-supplied vertex if it exists in the schema;
 *  2. `schema.protocol` (some builders use the protocol name as the
 *  top-level vertex id);
 *  3. the schema's declared primary entry (the pointed-schema
 *  basepoint).
 */
int32_t
pp_inst_json_to_instance (
    uint32_t schema_handle,
    slice_ref_uint8_t json,
    slice_ref_uint8_t root_vertex,
    Vec_uint8_t * out);

/** \brief
 *  Convert a W-type instance to JSON bytes.
 *
 *  `schema_handle` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle. `instance` is a CBOR-encoded `WInstance`. On success, `out`
 *  receives the JSON bytes (not CBOR). Calls `inst::to_json`.
 */
int32_t
pp_inst_to_json (
    uint32_t schema_handle,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  Validate a W-type instance against a schema.
 *
 *  `schema_handle` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle. `instance` is a CBOR-encoded
 *  `panproto_core::inst::WInstance`. On success, `out` receives a
 *  CBOR-encoded `Vec<String>` of validation messages (empty means
 *  valid). Calls `inst::validate_wtype`.
 *
 *  The validation pass always returns [`PpStatus::Ok`] when it can run
 *  to completion: individual violations are reported as message
 *  strings, not as a failing status. A non-`Ok` status is reserved for
 *  inputs that prevent validation from running at all (an invalid
 *  handle, a non-`Schema` resource, or undecodable instance bytes).
 */
int32_t
pp_inst_validate (
    uint32_t schema_handle,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  Emit an instance to raw format bytes using a protocol codec.
 *
 *  `registry` is an I/O registry handle; `proto_name` is the UTF-8
 *  protocol name bytes; `schema_handle` is a schema handle; `instance` is
 *  the CBOR-encoded instance (`WInstance` or `FInstance`). On success,
 *  `out` receives the raw format bytes (not CBOR). Dispatches on
 *  `ProtocolRegistry::native_repr`, mirroring the WASM boundary's
 *  `emit_instance`.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a
 *  bad handle, [`PpStatus::Serialization`] if the instance bytes do not
 *  decode, and [`PpStatus::Operation`] if the protocol is unknown or the
 *  emit fails.
 */
int32_t
pp_io_emit_instance (
    uint32_t registry,
    slice_ref_uint8_t proto_name,
    uint32_t schema_handle,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  List all protocol names registered in an I/O registry.
 *
 *  `registry` is a [`Resource::IoRegistry`](crate::handle::Resource)
 *  handle. On success, `out` receives a CBOR-encoded `Vec<String>`. Calls
 *  `ProtocolRegistry::protocol_names`.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] if the
 *  handle is invalid or not an I/O registry.
 */
int32_t
pp_io_list_protocols (
    uint32_t registry,
    Vec_uint8_t * out);

/** \brief
 *  Parse raw format bytes into an instance using a protocol codec.
 *
 *  `registry` is an I/O registry handle; `proto_name` is the UTF-8
 *  protocol name bytes; `schema_handle` is a
 *  [`Resource::Schema`](crate::handle::Resource) handle; `input` is the
 *  raw format bytes. On success, `out` receives the CBOR-encoded instance
 *  (`WInstance` or `FInstance`, per the protocol's native representation).
 *  Dispatches on `ProtocolRegistry::native_repr`, mirroring the WASM
 *  boundary's `parse_instance`.
 *
 *  Returns [`PpStatus::InvalidHandle`] / [`PpStatus::TypeMismatch`] for a
 *  bad handle, and [`PpStatus::Operation`] if the protocol is unknown or
 *  the parse fails.
 */
int32_t
pp_io_parse_instance (
    uint32_t registry,
    slice_ref_uint8_t proto_name,
    uint32_t schema_handle,
    slice_ref_uint8_t input,
    Vec_uint8_t * out);

/** \brief
 *  Create an I/O protocol registry with all built-in protocol codecs.
 *
 *  On success, `out_handle` receives a fresh
 *  [`Resource::IoRegistry`](crate::handle::Resource) handle holding
 *  `io::default_registry()` and [`PpStatus::Ok`] is returned.
 */
int32_t
pp_io_register_protocols (
    uint32_t * out_handle);

/** \brief
 *  Take the last error envelope as a CBOR byte vector.
 *
 *  On `PpStatus::Ok`, `out` is populated with the freshly allocated
 *  bytes; the host must release them via [`pp_buf_free`]. If no error
 *  is pending, `out` receives an empty buffer and the status is
 *  [`PpStatus::Ok`].
 */
int32_t
pp_last_error_take (
    Vec_uint8_t * out);

/** \brief
 *  Auto-generate up to `top_n` ranked candidate lenses.
 *
 *  `schema1` and `schema2` are schema handles; `stringency` is the
 *  UTF-8 tier name. On success, `out` receives a CBOR-encoded
 *  `{ candidates, coerce_proposals }` record. Calls
 *  `lens::auto_generate_candidates`.
 *
 *  Each candidate entry carries its instantiable `chain`: the candidate's
 *  `ProtolensChain` serialized in the same JSON shape
 *  `ProtolensChain::to_json` emits, so the host can feed it back through
 *  `pp_protolens_from_json` and `pp_protolens_instantiate` to obtain a
 *  runnable lens. The score, coverage, quality, strategies, and per-step
 *  explanations travel alongside it.
 */
int32_t
pp_lens_auto_generate_candidates (
    uint32_t schema1,
    uint32_t schema2,
    uint32_t top_n,
    slice_ref_uint8_t stringency,
    Vec_uint8_t * out);

/** \brief
 *  Auto-generate a protolens chain between two schemas.
 *
 *  `schema1` and `schema2` are
 *  [`Resource::Schema`](crate::handle::Resource) handles; `stringency`
 *  is the UTF-8 tier name (`strict`/`balanced`/`lenient`/`exploratory`,
 *  empty for default). On success, `out_handle` receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle. Calls
 *  `lens::auto_generate`.
 */
int32_t
pp_lens_auto_generate_protolens (
    uint32_t schema1,
    uint32_t schema2,
    slice_ref_uint8_t stringency,
    uint32_t * out_handle);

/** \brief
 *  Check the `GetPut` lens law on a test instance.
 *
 *  Arguments and payload match [`pp_lens_check_laws`]. Calls
 *  `lens::check_get_put`.
 */
int32_t
pp_lens_check_get_put (
    uint32_t migration,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  Check both `GetPut` and `PutGet` lens laws on a test instance.
 *
 *  `migration` is a migration/lens handle; `instance` is a CBOR-encoded
 *  `WInstance`. On success, `out` receives a CBOR-encoded
 *  [`LawCheckResult`]. Calls `lens::check_laws`.
 */
int32_t
pp_lens_check_laws (
    uint32_t migration,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  Check the `PutGet` lens law on a test instance.
 *
 *  Arguments and payload match [`pp_lens_check_laws`]. Calls
 *  `lens::check_put_get`.
 */
int32_t
pp_lens_check_put_get (
    uint32_t migration,
    slice_ref_uint8_t instance,
    Vec_uint8_t * out);

/** \brief
 *  Compile a lens DSL document into a protolens chain.
 *
 *  `source` is UTF-8 DSL source; `format` is the UTF-8 format name
 *  (`json` or `yaml`); `body_vertex` is the UTF-8 parent vertex id for
 *  field-level steps. On success, `out_handle` receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle. Calls
 *  `panproto_core::lens_dsl::{eval, compile}`.
 *
 *  Nickel (`ncl`) is intentionally unsupported here, matching the WASM
 *  boundary: Nickel evaluation requires a filesystem for its contract
 *  imports, so callers precompile Nickel to JSON on the host.
 */
int32_t
pp_lens_compile_document (
    slice_ref_uint8_t source,
    slice_ref_uint8_t format,
    slice_ref_uint8_t body_vertex,
    uint32_t * out_handle);

/** \brief
 *  Compile a lens DSL document, resolving `compose` named references
 *  against a bundle of sibling documents.
 *
 *  `source`, `format`, and `body_vertex` match
 *  [`pp_lens_compile_document`]. `refs` is a CBOR-encoded
 *  `map<string, string>` from each referenced lens `id` to its document
 *  source (in the same `format`); a `compose` body's `ref` entries are
 *  resolved against this map. On success, `out_handle` receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle. Calls
 *  `panproto_core::lens_dsl::compile_with_refs`.
 *
 *  Nickel (`ncl`) is intentionally unsupported, matching
 *  [`pp_lens_compile_document`].
 */
int32_t
pp_lens_compile_document_with_refs (
    slice_ref_uint8_t source,
    slice_ref_uint8_t format,
    slice_ref_uint8_t body_vertex,
    slice_ref_uint8_t refs,
    uint32_t * out_handle);

/** \brief
 *  Compose two lenses sequentially.
 *
 *  `l1` and `l2` are migration/lens handles. On success, `out_handle`
 *  receives a fresh
 *  [`Resource::MigrationWithSchemas`](crate::handle::Resource) handle.
 *  Calls `lens::compose`.
 */
int32_t
pp_lens_compose (
    uint32_t l1,
    uint32_t l2,
    uint32_t * out_handle);

/** \brief
 *  Bidirectional get: extract a view and complement from a record.
 *
 *  `migration` is a migration/lens handle; `record` is a CBOR-encoded
 *  `WInstance`. On success, `out` receives a CBOR-encoded
 *  `{ view: WInstance, complement: Complement }`. Calls `lens::get`.
 */
int32_t
pp_lens_get_record (
    uint32_t migration,
    slice_ref_uint8_t record,
    Vec_uint8_t * out);

/** \brief
 *  Bidirectional put: restore a record from a view and complement.
 *
 *  `migration` is a migration/lens handle; `view` and `complement` are
 *  CBOR-encoded `WInstance` and `Complement`. On success, `out`
 *  receives the CBOR-encoded restored `WInstance`. Calls `lens::put`.
 */
int32_t
pp_lens_put_record (
    uint32_t migration,
    slice_ref_uint8_t view,
    slice_ref_uint8_t complement,
    Vec_uint8_t * out);

/** \brief
 *  Auto-generate a symmetric lens from two schemas.
 *
 *  `schema1` and `schema2` are
 *  [`Resource::Schema`](crate::handle::Resource) handles. On success,
 *  `out_handle` receives a fresh
 *  [`Resource::SymmetricLensHandle`](crate::handle::Resource) handle.
 *  Calls `SymmetricLens::auto_symmetric`.
 */
int32_t
pp_lens_symmetric_from_schemas (
    uint32_t schema1,
    uint32_t schema2,
    uint32_t * out_handle);

/** \brief
 *  Sync data through a symmetric lens.
 *
 *  `sym_lens` is a symmetric-lens handle; `view` and `complement` are
 *  CBOR-encoded `WInstance` and `Complement`; `direction` is `0`
 *  (left-to-right) or `1` (right-to-left). On success, `out` receives
 *  the CBOR-encoded synced `WInstance`. Calls
 *  `SymmetricLens::sync_left_to_right` / `sync_right_to_left`.
 */
int32_t
pp_lens_symmetric_sync (
    uint32_t sym_lens,
    slice_ref_uint8_t view,
    slice_ref_uint8_t complement,
    uint8_t direction,
    Vec_uint8_t * out);

/** \brief
 *  Check the existence conditions for a migration mapping between two
 *  schemas.
 *
 *  `proto` is a [`Resource::Protocol`](crate::handle::Resource) handle;
 *  `src` and `tgt` are [`Resource::Schema`](crate::handle::Resource)
 *  handles. `mapping` is a CBOR-encoded `panproto_core::mig::Migration`.
 *  On success, `out` receives a CBOR-encoded `mig::ExistenceReport`
 *  (the report itself encodes validity). Calls `mig::check_existence`
 *  with a theory registry from
 *  [`crate::api::helpers::build_theory_registry`].
 *
 *  Like `pp_inst_validate`, the check returns [`PpStatus::Ok`] whenever
 *  it can run to completion: a migration that fails the existence
 *  conditions is reported as `valid: false` inside the report, not as a
 *  failing status. A non-`Ok` status is reserved for inputs that
 *  prevent the check from running (an invalid handle, a non-`Protocol`
 *  or non-`Schema` resource, undecodable mapping bytes, or an
 *  unrecognized protocol whose theory registry cannot be built).
 */
int32_t
pp_mig_check_existence (
    uint32_t proto,
    uint32_t src,
    uint32_t tgt,
    slice_ref_uint8_t mapping,
    Vec_uint8_t * out);

/** \brief
 *  Compile a migration for fast per-record application.
 *
 *  `src` and `tgt` are [`Resource::Schema`](crate::handle::Resource)
 *  handles. `mapping` is a CBOR-encoded `mig::Migration`. On success,
 *  `out_handle` receives a fresh
 *  [`Resource::MigrationWithSchemas`](crate::handle::Resource) handle.
 *  Calls `mig::compile`.
 */
int32_t
pp_mig_compile (
    uint32_t src,
    uint32_t tgt,
    slice_ref_uint8_t mapping,
    uint32_t * out_handle);

/** \brief
 *  Compose two compiled migrations into a single migration.
 *
 *  `m1` and `m2` are migration handles (either
 *  [`Resource::Migration`](crate::handle::Resource) or
 *  `MigrationWithSchemas`). On success, `out_handle` receives a fresh
 *  [`Resource::Migration`](crate::handle::Resource) handle. Calls
 *  [`crate::api::helpers::compose_compiled`].
 */
int32_t
pp_mig_compose (
    uint32_t m1,
    uint32_t m2,
    uint32_t * out_handle);

/** \brief
 *  Run coverage analysis (dry-run migration) over a batch of instances.
 *
 *  `migration` is a migration handle; `src` and `tgt` are
 *  [`Resource::Schema`](crate::handle::Resource) handles. `instances`
 *  is a CBOR-encoded `Vec<WInstance>`. On success, `out` receives a
 *  CBOR-encoded coverage report (`total`, `succeeded`, `failed`,
 *  `coverage_percent`, `errors`, plus source and target vertex counts).
 *  Calls `mig::lift_wtype` per record.
 */
int32_t
pp_mig_coverage (
    uint32_t migration,
    uint32_t src,
    uint32_t tgt,
    slice_ref_uint8_t instances,
    Vec_uint8_t * out);

/** \brief
 *  Invert a bijective migration.
 *
 *  `mapping` is a CBOR-encoded `mig::Migration`; `src` and `tgt` are
 *  [`Resource::Schema`](crate::handle::Resource) handles. On success,
 *  `out` receives the CBOR-encoded inverse `mig::Migration`. Calls
 *  `mig::invert` and fails with [`PpStatus::Operation`] when the
 *  migration is not invertible.
 */
int32_t
pp_mig_invert (
    slice_ref_uint8_t mapping,
    uint32_t src,
    uint32_t tgt,
    Vec_uint8_t * out);

/** \brief
 *  Lift a JSON record through a compiled migration, returning JSON.
 *
 *  `migration` is a migration handle. `json` is raw JSON bytes (decoded
 *  with `serde_json`, not CBOR). `root_vertex` is the source schema
 *  vertex the JSON object maps to (empty auto-detects). On success,
 *  `out` receives the migrated record as JSON bytes. Calls
 *  `inst::parse_json`, `mig::lift_wtype`, then `inst::to_json`.
 *
 *  Root-vertex resolution mirrors `pp_inst_json_to_instance`: the
 *  explicit vertex when present, then the source schema's protocol name
 *  when it names a vertex, then the schema's declared primary entry.
 */
int32_t
pp_mig_lift_json (
    uint32_t migration,
    slice_ref_uint8_t json,
    slice_ref_uint8_t root_vertex,
    Vec_uint8_t * out);

/** \brief
 *  Apply a compiled migration to a single W-type record.
 *
 *  `migration` is a [`Resource::Migration`](crate::handle::Resource)
 *  (or `MigrationWithSchemas`) handle. `record` is a CBOR-encoded
 *  `panproto_core::inst::WInstance`. On success, `out` receives the
 *  CBOR-encoded migrated instance. Calls `mig::lift_wtype` via
 *  [`crate::api::helpers::extract_migration_ref`].
 */
int32_t
pp_mig_lift_record (
    uint32_t migration,
    slice_ref_uint8_t record,
    Vec_uint8_t * out);

/** \brief
 *  Serialize a compiled migration to CBOR.
 *
 *  `mig_handle` is a [`Resource::Migration`](crate::handle::Resource)
 *  or [`Resource::MigrationWithSchemas`](crate::handle::Resource)
 *  handle. On success, `out` receives the CBOR-encoded
 *  `panproto_core::inst::CompiledMigration` (the `compiled` payload, not
 *  the anchoring schemas). This is the byte form the graph domain
 *  consumes: `pp_graph_fiber_at` and `pp_graph_fiber_decomposition`
 *  take their `migration` argument as exactly these bytes.
 *
 *  Fails with [`PpStatus::InvalidHandle`] or [`PpStatus::TypeMismatch`]
 *  when the handle does not resolve to a migration.
 */
int32_t
pp_mig_serialize_compiled (
    uint32_t mig_handle,
    Vec_uint8_t * out);

/** \brief
 *  Ingest a CBOR-encoded [`Protocol`] specification and register it
 *  in the slab.
 *
 *  On success, `out_handle` is set to a fresh handle and [`PpStatus::Ok`]
 *  is returned. On CBOR decode failure, [`PpStatus::Serialization`] is
 *  returned and `out_handle` is left untouched.
 */
int32_t
pp_protocol_define (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Serialize the protocol referenced by `proto` to CBOR.
 *
 *  On success, `out` is populated with freshly allocated CBOR bytes;
 *  the host must release them via `pp_buf_free`. Common failure modes
 *  are [`PpStatus::InvalidHandle`] and (once additional resource
 *  variants exist) [`PpStatus::TypeMismatch`].
 */
int32_t
pp_protocol_serialize (
    uint32_t proto,
    Vec_uint8_t * out);

/** \brief
 *  Serialize a protolens chain to JSON.
 *
 *  `chain` is a protolens chain handle. On success, `out` receives JSON
 *  bytes describing each step (name, endofunctors, lossless flag) per
 *  [`ProtolensStepInfo`].
 */
int32_t
pp_protolens_chain_to_json (
    uint32_t chain,
    Vec_uint8_t * out);

/** \brief
 *  Get the complement spec for a protolens chain at a schema.
 *
 *  `chain` is a protolens chain handle; `schema` is a schema handle. On
 *  success, `out` receives a CBOR-encoded
 *  `panproto_core::lens::ComplementSpec`. Calls
 *  `lens::chain_complement_spec`.
 */
int32_t
pp_protolens_complement_spec (
    uint32_t chain,
    uint32_t schema,
    Vec_uint8_t * out);

/** \brief
 *  Compose two protolens chains.
 *
 *  `chain1` and `chain2` are protolens chain handles. On success,
 *  `out_handle` receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle holding
 *  the concatenated steps.
 */
int32_t
pp_protolens_compose (
    uint32_t chain1,
    uint32_t chain2,
    uint32_t * out_handle);

/** \brief
 *  Build a protolens chain from a diff spec.
 *
 *  `diff` is a CBOR-encoded `panproto_core::lens::DiffSpec`; `schema1`
 *  and `schema2` are schema handles. On success, `out_handle` receives
 *  a fresh [`Resource::ProtolensChain`](crate::handle::Resource)
 *  handle. Calls `lens::diff_to_protolens`.
 */
int32_t
pp_protolens_from_diff (
    slice_ref_uint8_t diff,
    uint32_t schema1,
    uint32_t schema2,
    uint32_t * out_handle);

/** \brief
 *  Deserialize a protolens chain from JSON.
 *
 *  `json` is raw JSON bytes. On success, `out_handle` receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle. Calls
 *  `ProtolensChain::from_json`.
 */
int32_t
pp_protolens_from_json (
    slice_ref_uint8_t json,
    uint32_t * out_handle);

/** \brief
 *  Fuse a protolens chain into a single composite step.
 *
 *  `chain` is a protolens chain handle. On success, `out_handle`
 *  receives a fresh
 *  [`Resource::ProtolensChain`](crate::handle::Resource) handle holding
 *  the fused step. Calls `ProtolensChain::fuse`.
 */
int32_t
pp_protolens_fuse (
    uint32_t chain,
    uint32_t * out_handle);

/** \brief
 *  Instantiate a protolens chain at a specific schema.
 *
 *  `chain` is a [`Resource::ProtolensChain`](crate::handle::Resource)
 *  handle; `schema` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle. On success, `out_handle` receives a fresh
 *  [`Resource::MigrationWithSchemas`](crate::handle::Resource) handle.
 *  Calls `ProtolensChain::instantiate`.
 */
int32_t
pp_protolens_instantiate (
    uint32_t chain,
    uint32_t schema,
    uint32_t * out_handle);

/** \brief
 *  Execute a declarative query against a W-type instance.
 *
 *  `query` is a CBOR-encoded [`inst::InstanceQuery`]; `instance` is a
 *  CBOR-encoded [`WInstance`]; `schema_handle` is a
 *  [`Resource::Schema`](crate::handle::Resource) handle. On success,
 *  `out` receives a CBOR-encoded list of match records, each a map with
 *  `node_id`, `anchor`, `value`, and `fields`. Calls
 *  [`inst::execute_query`].
 *
 *  The schema handle must resolve to a
 *  [`Resource::Schema`](crate::handle::Resource); a bad handle yields
 *  [`PpStatus::InvalidHandle`] and a wrong resource type yields
 *  [`PpStatus::TypeMismatch`].
 */
int32_t
pp_query_execute (
    slice_ref_uint8_t query,
    slice_ref_uint8_t instance,
    uint32_t schema_handle,
    Vec_uint8_t * out);

/** \brief
 *  Get a built-in protocol specification by name.
 *
 *  `name` is the UTF-8 protocol name bytes. On success, `out` receives
 *  the CBOR-encoded `panproto_core::schema::Protocol`. Calls
 *  [`crate::api::helpers::lookup_builtin_protocol`].
 *
 *  Returns [`PpStatus::Operation`] if the name is not a recognized
 *  built-in protocol.
 */
int32_t
pp_registry_get_builtin (
    slice_ref_uint8_t name,
    Vec_uint8_t * out);

/** \brief
 *  List all built-in semantic protocol names.
 *
 *  On success, `out` receives a CBOR-encoded `Vec<String>`. Calls
 *  [`crate::api::helpers::builtin_protocol_names`].
 */
int32_t
pp_registry_list_builtin (
    Vec_uint8_t * out);

/** \brief
 *  Add a coercion between two vertex kinds to a schema.
 *
 *  `schema_handle` is a [`Resource::Schema`](crate::handle::Resource)
 *  handle; `from_kind` and `to_kind` are the UTF-8 source/target vertex
 *  kind names; `expr` is a CBOR-encoded `panproto_core::expr::Expr` coercion
 *  expression. On success, `out_handle` receives a fresh
 *  [`Resource::Schema`](crate::handle::Resource) handle with the
 *  coercion installed (as a `CoercionClass::Opaque` coercion with no
 *  inverse), keyed by the `(from_kind, to_kind)` pair.
 */
int32_t
pp_schema_add_coercion (
    uint32_t schema_handle,
    slice_ref_uint8_t from_kind,
    slice_ref_uint8_t to_kind,
    slice_ref_uint8_t expr,
    uint32_t * out_handle);

/** \brief
 *  Add a default value to a schema vertex.
 *
 *  `schema_handle` is a schema handle; `vertex_name` is the UTF-8 vertex
 *  name; `expr` is a CBOR-encoded `panproto_core::inst::value::Value`.
 *  The default is recorded as a `default` constraint annotation on the
 *  vertex. On success, `out_handle` receives a fresh
 *  [`Resource::Schema`](crate::handle::Resource) handle.
 */
int32_t
pp_schema_add_default (
    uint32_t schema_handle,
    slice_ref_uint8_t vertex_name,
    slice_ref_uint8_t expr,
    uint32_t * out_handle);

/** \brief
 *  Add a merger annotation to a schema vertex.
 *
 *  `schema_handle` is a schema handle; `vertex_name` is the UTF-8 vertex
 *  name; `spec` is a CBOR-encoded `{ strategy, args }` record. The
 *  merger is recorded as a `merger` constraint annotation. On success,
 *  `out_handle` receives a fresh
 *  [`Resource::Schema`](crate::handle::Resource) handle.
 */
int32_t
pp_schema_add_merger (
    uint32_t schema_handle,
    slice_ref_uint8_t vertex_name,
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Add a conflict policy annotation to a schema vertex.
 *
 *  `schema_handle` is a schema handle; `vertex_name` is the UTF-8 vertex
 *  name; `spec` is a CBOR-encoded `{ policy }` record. The policy is
 *  recorded as a `conflict_policy` constraint annotation. On success,
 *  `out_handle` receives a fresh
 *  [`Resource::Schema`](crate::handle::Resource) handle.
 */
int32_t
pp_schema_add_policy (
    uint32_t schema_handle,
    slice_ref_uint8_t vertex_name,
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Build a schema from a protocol handle and a CBOR-encoded list of
 *  builder operations.
 *
 *  `proto` is a [`Resource::Protocol`] handle. `ops` is a CBOR-encoded
 *  `Vec<BuildOp>` (see [`crate::api::helpers::BuildOp`]). On success,
 *  `out_handle` receives a fresh [`Resource::Schema`] handle. The ops
 *  are run through [`crate::api::helpers::build_schema_from_ops`].
 */
int32_t
pp_schema_build (
    uint32_t proto,
    slice_ref_uint8_t ops,
    uint32_t * out_handle);

/** \brief
 *  Deserialize a CBOR-encoded `Schema` into the slab.
 *
 *  On success, `out_handle` is set to a fresh handle and
 *  [`PpStatus::Ok`] is returned. On CBOR decode failure,
 *  [`PpStatus::Serialization`] is returned and `out_handle` is left
 *  untouched.
 */
int32_t
pp_schema_from_cbor (
    slice_ref_uint8_t spec,
    uint32_t * out_handle);

/** \brief
 *  Extract schema metadata (protocol name, vertices, edges) as CBOR.
 *
 *  `schema_handle` is a [`Resource::Schema`] handle. On success, `out`
 *  receives a CBOR-encoded metadata record mirroring the WASM
 *  `schema_metadata` payload (`{ protocol, vertices, edges }`).
 */
int32_t
pp_schema_metadata (
    uint32_t schema_handle,
    Vec_uint8_t * out);

/** \brief
 *  Normalize a schema by collapsing reference chains.
 *
 *  `schema_handle` is a [`Resource::Schema`] handle. On success,
 *  `out_handle` receives a fresh [`Resource::Schema`] handle for the
 *  normalized schema. Calls `panproto_core::schema::normalize`.
 */
int32_t
pp_schema_normalize (
    uint32_t schema_handle,
    uint32_t * out_handle);

/** \brief
 *  Parse an `ATProto` lexicon JSON document into a schema.
 *
 *  `json` is raw JSON bytes (decoded with `serde_json`, not CBOR). On
 *  success, `out_handle` receives a fresh [`Resource::Schema`] handle.
 *  Calls `panproto_core::protocols::atproto::parse_lexicon`.
 */
int32_t
pp_schema_parse_atproto_lexicon (
    slice_ref_uint8_t json,
    uint32_t * out_handle);

/** \brief
 *  Serialize the schema referenced by `schema_handle` to CBOR.
 *
 *  On success, `out` is populated with freshly allocated CBOR bytes;
 *  the host must release them via `pp_buf_free`. Common failure modes
 *  are [`PpStatus::InvalidHandle`] and [`PpStatus::TypeMismatch`]
 *  (when `schema_handle` does not point at a `Schema` resource).
 */
int32_t
pp_schema_to_cbor (
    uint32_t schema_handle,
    Vec_uint8_t * out);

/** \brief
 *  Validate the schema referenced by `schema_handle` against the
 *  protocol referenced by `proto_handle`.
 *
 *  `out_messages` is populated with a CBOR-encoded `Vec<String>` of
 *  human-readable validation messages. An empty list means the schema
 *  is valid against the protocol. The status is always [`PpStatus::Ok`]
 *  on a successful validation pass (regardless of whether the schema
 *  passed validation); validation failures appear in the message list.
 *  Status [`PpStatus::Err`] is reserved for cases where validation
 *  could not run at all (e.g. a typed-mismatch handle).
 *
 *  Both handles must outlive the call. Common failure modes are
 *  [`PpStatus::InvalidHandle`] and [`PpStatus::TypeMismatch`].
 */
int32_t
pp_schema_validate (
    uint32_t schema_handle,
    uint32_t proto_handle,
    Vec_uint8_t * out_messages);

/** \brief
 *  Stage a schema in a VCS repository.
 *
 *  `repo` is a VCS repo handle; `schema` is a
 *  [`Resource::Schema`](crate::handle::Resource) handle. On success,
 *  `out` receives a CBOR-encoded add result carrying the staged schema's
 *  object id, whether a migration from HEAD was auto-derived, the
 *  validation verdict, and any validation messages. Calls
 *  `Repository::add`.
 */
int32_t
pp_vcs_add (
    uint32_t repo,
    uint32_t schema,
    Vec_uint8_t * out);

/** \brief
 *  Blame a vertex: find the commit that introduced it.
 *
 *  `repo` is a VCS repo handle; `vertex` is the UTF-8 vertex ID. Calls
 *  `vcs::blame::blame_vertex` from HEAD. On success, `out` receives a
 *  CBOR-encoded blame record.
 */
int32_t
pp_vcs_blame (
    uint32_t repo,
    slice_ref_uint8_t vertex,
    Vec_uint8_t * out);

/** \brief
 *  Create a new branch from HEAD.
 *
 *  `repo` is a VCS repo handle; `name` is the UTF-8 branch name. Calls
 *  `vcs::refs::create_branch` against the current HEAD commit, then
 *  returns the full branch listing as a CBOR-encoded branch result so
 *  the caller sees the new branch in context.
 */
int32_t
pp_vcs_branch (
    uint32_t repo,
    slice_ref_uint8_t name,
    Vec_uint8_t * out);

/** \brief
 *  Checkout a branch or commit.
 *
 *  `repo` is a VCS repo handle; `target` is the UTF-8 branch/commit
 *  reference. Calls `vcs::refs::checkout_branch`, then reports the
 *  resulting HEAD state as a CBOR-encoded op result.
 */
int32_t
pp_vcs_checkout (
    uint32_t repo,
    slice_ref_uint8_t target,
    Vec_uint8_t * out);

/** \brief
 *  Commit the staged schema in a VCS repository.
 *
 *  `repo` is a VCS repo handle; `message` and `author` are UTF-8 bytes.
 *  Calls `Repository::commit`, which builds a commit from the staging
 *  index and advances HEAD. On success, `out` receives a CBOR-encoded
 *  commit result carrying the new commit id, the recorded message and
 *  author, and the commit timestamp.
 *
 *  Returns [`PpStatus::Operation`] when there is nothing staged or when
 *  GAT validation blocks the commit.
 */
int32_t
pp_vcs_commit (
    uint32_t repo,
    slice_ref_uint8_t message,
    slice_ref_uint8_t author,
    Vec_uint8_t * out);

/** \brief
 *  Structural diff between two refs, or of the most recent schema change
 *  at HEAD.
 *
 *  `repo` is a VCS repo handle; `from` and `to` are UTF-8 refs (a branch
 *  name, tag name, or full hex commit id). When both are empty, the HEAD
 *  commit's schema is diffed against its first parent's schema via
 *  `panproto_check::diff`, surfacing the change the latest commit
 *  introduced (a root commit is diffed against the empty schema, so every
 *  element reads as added; an empty repository yields a zero-change
 *  record). When at least one ref is non-empty, each is resolved through
 *  `vcs::refs::resolve_ref` to a commit and its schema is assembled; an
 *  empty ref on either side resolves to the empty schema, so a single ref
 *  diffs that revision against nothing. On success, `out` receives a
 *  CBOR-encoded diff record carrying the added / removed / modified counts
 *  and the human-readable change descriptions.
 */
int32_t
pp_vcs_diff (
    uint32_t repo,
    slice_ref_uint8_t from,
    slice_ref_uint8_t to,
    Vec_uint8_t * out);

/** \brief
 *  Open or initialize an on-disk VCS repository at a filesystem path.
 *
 *  `path` is the UTF-8 path bytes of the repository's working directory.
 *  If a `.panproto/` store already exists there, the repository is opened
 *  via `Repository::open`; otherwise it is created via `Repository::init`
 *  (which writes the `.panproto/` directory structure and sets HEAD to
 *  `main`). On success, `out_handle` receives a fresh
 *  [`Resource::VcsRepo`](crate::handle::Resource) handle wrapping the
 *  `Repository`.
 */
int32_t
pp_vcs_init (
    slice_ref_uint8_t path,
    uint32_t * out_handle);

/** \brief
 *  List all branches and the commit each points at.
 *
 *  `repo` is a VCS repo handle. Calls `vcs::refs::list_branches` and
 *  reports the full branch listing as a CBOR-encoded branch result,
 *  tagging the branch HEAD currently tracks. An empty repository (no
 *  branches yet) yields an empty listing. This is the create-free
 *  listing op; `pp_vcs_branch` creates a branch and returns the same
 *  listing shape after the create.
 */
int32_t
pp_vcs_list_branches (
    uint32_t repo,
    Vec_uint8_t * out);

/** \brief
 *  Walk the commit log from HEAD.
 *
 *  `repo` is a VCS repo handle; `count` caps the walk length. On success,
 *  `out` receives a CBOR-encoded log result (a map with an `entries`
 *  list, newest first). Calls `Repository::log`. Each entry's
 *  `commit_id` is recomputed from the commit object via
 *  `vcs::hash::hash_commit` (the `CommitObject` does not carry its own
 *  id). An empty repository yields an empty entry list.
 */
int32_t
pp_vcs_log (
    uint32_t repo,
    uint32_t count,
    Vec_uint8_t * out);

/** \brief
 *  Merge a branch into the current branch.
 *
 *  `repo` is a VCS repo handle; `branch` is the UTF-8 branch name;
 *  `author` is the UTF-8 author the merge commit is attributed to. Calls
 *  `Repository::merge`, a real three-way merge that fast-forwards or
 *  creates a merge commit as appropriate. The merge commit (when one is
 *  created) records `author`. On success, `out` receives a CBOR-encoded
 *  merge result carrying the fast-forward flag, the resulting HEAD
 *  commit, and the conflict descriptions (empty on a clean merge).
 */
int32_t
pp_vcs_merge (
    uint32_t repo,
    slice_ref_uint8_t branch,
    slice_ref_uint8_t author,
    Vec_uint8_t * out);

/** \brief
 *  Stash the current staged schema.
 *
 *  `repo` is a VCS repo handle. Pushes the currently staged schema onto
 *  the stash stack via `vcs::stash::stash_push`, clears the staging
 *  index, and reports the new stash entry plus the full stack. On
 *  success, `out` receives a CBOR-encoded stash result.
 *
 *  Returns [`PpStatus::Operation`] when there is nothing staged to stash.
 */
int32_t
pp_vcs_stash (
    uint32_t repo,
    Vec_uint8_t * out);

/** \brief
 *  Pop the most recent stash entry.
 *
 *  `repo` is a VCS repo handle. Calls `vcs::stash::stash_pop`, restoring
 *  the schema staged in the popped stash into the index, then reports
 *  the restored schema id and the remaining stack as a CBOR-encoded
 *  stash-pop result.
 */
int32_t
pp_vcs_stash_pop (
    uint32_t repo,
    Vec_uint8_t * out);

/** \brief
 *  Get repository status (HEAD, staging, working state).
 *
 *  `repo` is a VCS repo handle. On success, `out` receives a
 *  CBOR-encoded status record: HEAD state, the resolved HEAD commit
 *  (absent for an empty repo), and `has_staged` / `working_dirty`
 *  booleans read from the staging index.
 */
int32_t
pp_vcs_status (
    uint32_t repo,
    Vec_uint8_t * out);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_PANPROTO_C__ */
