/*! \file
 *
 *  Declarations for the feature-gated panproto-c entry points.
 *
 *  `panproto.h` is generated by `safer-ffi` from a default-feature
 *  build, so it covers only the 103 symbols the default cdylib
 *  exports. The `full-parse`, `project`, and `git` features add 17
 *  more, and `safer-ffi` cannot emit them into the same header
 *  without a feature-matrix of generated headers. They are declared
 *  here instead, in the same order and with the same signatures the
 *  crate's `#[ffi_export]` attributes produce.
 *
 *  Declaring a symbol costs nothing at build time: the Swift shims
 *  that reference these live behind `#if PANPROTO_PARSE`,
 *  `#if PANPROTO_PROJECT`, and `#if PANPROTO_GIT`, so a package built
 *  against the default library never emits an undefined reference.
 *  Link a `full`-feature libpanproto_c and set the matching feature
 *  the matching package trait to reach them.
 *
 *  Keep this file in step with `crates/panproto-c/src/api/parse.rs`,
 *  `project.rs`, and `git.rs`; the parity gate in
 *  `Scripts/parity-gate.py` checks that every documented entry point
 *  has both a declaration and a Swift shim.
 */

#ifndef __PANPROTO_C_GATED__
#define __PANPROTO_C_GATED__

#include "panproto.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------- */
/* parse (10) -- feature `full-parse`                                */
/* ---------------------------------------------------------------- */

/** \brief Create a new `AstRegistry` handle (`ParserRegistry::new`). */
int32_t
pp_parse_registry_new (
    uint32_t * out_handle);

/** \brief Parse a source file into a new `Schema` handle, dispatching
 *  on the path's extension (`ParserRegistry::parse_file`). */
int32_t
pp_parse_file (
    uint32_t registry,
    slice_ref_uint8_t path,
    slice_ref_uint8_t content,
    uint32_t * out_handle);

/** \brief Parse source bytes with an explicitly named protocol
 *  (`ParserRegistry::parse_with_protocol`). */
int32_t
pp_parse_with_protocol (
    uint32_t registry,
    slice_ref_uint8_t protocol,
    slice_ref_uint8_t content,
    slice_ref_uint8_t file_path,
    uint32_t * out_handle);

/** \brief Detect the protocol name for a path; the output buffer is
 *  empty when no grammar claims the extension. */
int32_t
pp_parse_detect_language (
    uint32_t registry,
    slice_ref_uint8_t path,
    Vec_uint8_t * out);

/** \brief Emit source bytes for a parsed schema (`emit_with_protocol`). */
int32_t
pp_parse_emit (
    uint32_t registry,
    slice_ref_uint8_t protocol,
    uint32_t schema,
    Vec_uint8_t * out);

/** \brief Emit re-formatted source bytes
 *  (`emit_pretty_with_protocol`). */
int32_t
pp_parse_emit_pretty (
    uint32_t registry,
    slice_ref_uint8_t protocol,
    uint32_t schema,
    Vec_uint8_t * out);

/** \brief CBOR `Vec<String>` of the registry's protocol names. */
int32_t
pp_parse_protocol_names (
    uint32_t registry,
    Vec_uint8_t * out);

/** \brief CBOR `Vec<String>` of the grammars compiled into the
 *  library (`panproto_grammars::grammars`). */
int32_t
pp_parse_available_grammars (
    Vec_uint8_t * out);

/** \brief Check `parse(emit(schema)) == schema`; an empty output
 *  buffer means the law holds, otherwise it carries divergence text. */
int32_t
pp_parse_check_emit_parse (
    uint32_t registry,
    slice_ref_uint8_t protocol,
    uint32_t schema,
    Vec_uint8_t * out);

/** \brief Check `emit(parse(bytes)) == bytes`; an empty output buffer
 *  means the law holds, otherwise it carries divergence text. */
int32_t
pp_parse_check_parse_emit (
    uint32_t registry,
    slice_ref_uint8_t protocol,
    slice_ref_uint8_t bytes,
    Vec_uint8_t * out);

/* ---------------------------------------------------------------- */
/* project (6) -- feature `project`                                  */
/* ---------------------------------------------------------------- */

/** \brief Create a new `ProjectBuilder` handle. */
int32_t
pp_project_builder_new (
    uint32_t * out_handle);

/** \brief Add one file's contents to the builder, in place. */
int32_t
pp_project_add_file (
    uint32_t builder,
    slice_ref_uint8_t path,
    slice_ref_uint8_t content);

/** \brief Add a directory tree to the builder, in place. */
int32_t
pp_project_add_directory (
    uint32_t builder,
    slice_ref_uint8_t path);

/** \brief Build the accumulated files into a `ProjectSchema` handle. */
int32_t
pp_project_build (
    uint32_t builder,
    uint32_t * out_handle);

/** \brief Take the project's coproduct `Schema` as a new handle. */
int32_t
pp_project_schema_get (
    uint32_t project,
    uint32_t * out_handle);

/** \brief CBOR `HashMap<String, String>` mapping path to protocol. */
int32_t
pp_project_protocol_map (
    uint32_t project,
    Vec_uint8_t * out);

/* ---------------------------------------------------------------- */
/* git (1) -- feature `git`                                          */
/* ---------------------------------------------------------------- */

/** \brief Import an on-disk git repository into a new `VcsRepo`
 *  handle, plus a CBOR `{ commit_count, head_id }` summary. */
int32_t
pp_git_import (
    slice_ref_uint8_t repo_path,
    slice_ref_uint8_t revspec,
    uint32_t * out_handle,
    Vec_uint8_t * out);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __PANPROTO_C_GATED__ */
